import { LanguageCode } from '@/utils/constants';

export const onboardingCopy = {
  en: {
    stepLabel: (step: number, total: number) => `Step ${step} of ${total}`,
    busy: 'Please wait...',
    error: 'Something went wrong. You can try again.',
    back: 'Go back',
    welcomeSubtitle: 'Your AI learning companion',
    getStarted: 'Get Started',
    welcomeTitle: 'Welcome to Lernzy',
    welcomeBody: 'Learn mathematics, science, English, and more in a flow tailored to your class and interests.',
    languageTitle: 'Choose Language',
    languageSubtitle: 'Pick the language Lernzy should use while teaching you.',
    continue: 'Continue',
    languages: {
      en: { title: 'English', subtitle: 'Use English for lessons and menus' },
      hi: { title: 'Hindi', subtitle: 'Use Hindi for lessons and menus' },
      kn: { title: 'Kannada', subtitle: 'Use Kannada for lessons and menus' },
    },
    nameTitle: 'What is your name?',
    nameSubtitle: 'Your tutor will use this to make lessons feel personal.',
    namePlaceholder: 'Enter your name',
    next: 'Next',
    gradeTitle: 'Select Your Class',
    gradeSubtitle: 'Lernzy will match examples and practice to your level.',
    classLabel: (grade: number) => `Class ${grade}`,
    interestsTitle: 'What Do You Like?',
    interestsSubtitle: 'Pick at least one. Lernzy will use these interests in examples.',
    interests: {
      space: { title: 'Space', subtitle: 'Planets, rockets, and stars' },
      nature: { title: 'Nature', subtitle: 'Plants and the natural world' },
      robots: { title: 'Technology', subtitle: 'Computers, robots, and apps' },
      sports: { title: 'Sports', subtitle: 'Games, scores, and teamwork' },
      stories: { title: 'Stories', subtitle: 'Characters, poems, and ideas' },
      history: { title: 'History', subtitle: 'Places, people, and events' },
    },
    learningTitle: 'How Do You Learn Best?',
    learningSubtitle: 'Choose one style. You can change this later.',
    learningStyles: {
      reading: { title: 'Read and Understand', subtitle: 'Clear notes, stories, and diagrams.' },
      audio: { title: 'Listen and Learn', subtitle: 'Audio-friendly lessons and explanations.' },
      quiz: { title: 'Practice and Play', subtitle: 'Quizzes, cards, and quick challenges.' },
    },
    doneTitleReady: 'You Are Ready',
    doneTitleLoading: 'Setting Things Up',
    doneSubtitleReady: 'Your learning space is ready.',
    doneSubtitleLoading: 'Preparing your local learning profile.',
    startLearning: 'Start Learning',
    preparing: 'Preparing...',
    doneOk: 'OK',
    doneBodyReady: 'You can now explore lessons, quizzes, progress, and review cards.',
    doneBodyLoading: 'This only takes a moment.',
  },
  hi: {
    stepLabel: (step: number, total: number) => `चरण ${step} / ${total}`,
    busy: 'कृपया प्रतीक्षा करें...',
    error: 'कुछ गलत हो गया। फिर कोशिश करें।',
    back: 'पीछे जाएं',
    welcomeSubtitle: 'आपका AI सीखने वाला साथी',
    getStarted: 'शुरू करें',
    welcomeTitle: 'Lernzy में आपका स्वागत है',
    welcomeBody: 'गणित, विज्ञान, अंग्रेजी और अन्य विषय अपनी कक्षा और रुचियों के अनुसार सीखें।',
    languageTitle: 'भाषा चुनें',
    languageSubtitle: 'वह भाषा चुनें जिसमें Lernzy आपको पढ़ाए।',
    continue: 'आगे बढ़ें',
    languages: {
      en: { title: 'English', subtitle: 'पाठ और मेनू के लिए English उपयोग करें' },
      hi: { title: 'Hindi', subtitle: 'पाठ और मेनू के लिए Hindi उपयोग करें' },
      kn: { title: 'Kannada', subtitle: 'पाठ और मेनू के लिए Kannada उपयोग करें' },
    },
    nameTitle: 'आपका नाम क्या है?',
    nameSubtitle: 'आपका ट्यूटर पाठों को व्यक्तिगत बनाने के लिए इसका उपयोग करेगा।',
    namePlaceholder: 'अपना नाम लिखें',
    next: 'आगे',
    gradeTitle: 'अपनी कक्षा चुनें',
    gradeSubtitle: 'Lernzy आपके स्तर के अनुसार उदाहरण और अभ्यास देगा।',
    classLabel: (grade: number) => `कक्षा ${grade}`,
    interestsTitle: 'आपको क्या पसंद है?',
    interestsSubtitle: 'कम से कम एक चुनें। Lernzy उदाहरणों में इन रुचियों का उपयोग करेगा।',
    interests: {
      space: { title: 'अंतरिक्ष', subtitle: 'ग्रह, रॉकेट और तारे' },
      nature: { title: 'प्रकृति', subtitle: 'पौधे और प्राकृतिक दुनिया' },
      robots: { title: 'तकनीक', subtitle: 'कंप्यूटर, रोबोट और ऐप्स' },
      sports: { title: 'खेल', subtitle: 'गेम, स्कोर और टीमवर्क' },
      stories: { title: 'कहानियां', subtitle: 'पात्र, कविताएं और विचार' },
      history: { title: 'इतिहास', subtitle: 'स्थान, लोग और घटनाएं' },
    },
    learningTitle: 'आप सबसे अच्छा कैसे सीखते हैं?',
    learningSubtitle: 'एक तरीका चुनें। आप इसे बाद में बदल सकते हैं।',
    learningStyles: {
      reading: { title: 'पढ़कर समझना', subtitle: 'स्पष्ट नोट्स, कहानियां और चित्र।' },
      audio: { title: 'सुनकर सीखना', subtitle: 'ऑडियो के लिए आसान पाठ और समझाइश।' },
      quiz: { title: 'अभ्यास और खेल', subtitle: 'क्विज, कार्ड और छोटे चैलेंज।' },
    },
    doneTitleReady: 'आप तैयार हैं',
    doneTitleLoading: 'सेटअप हो रहा है',
    doneSubtitleReady: 'आपकी सीखने की जगह तैयार है।',
    doneSubtitleLoading: 'आपकी स्थानीय सीखने वाली प्रोफाइल तैयार हो रही है।',
    startLearning: 'सीखना शुरू करें',
    preparing: 'तैयार हो रहा है...',
    doneOk: 'ठीक',
    doneBodyReady: 'अब आप पाठ, क्विज, प्रगति और रिव्यू कार्ड देख सकते हैं।',
    doneBodyLoading: 'इसमें बस एक पल लगेगा।',
  },
  kn: {
    stepLabel: (step: number, total: number) => `ಹಂತ ${step} / ${total}`,
    busy: 'ದಯವಿಟ್ಟು ಕಾಯಿರಿ...',
    error: 'ಏನೋ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    back: 'ಹಿಂದಕ್ಕೆ ಹೋಗಿ',
    welcomeSubtitle: 'ನಿಮ್ಮ AI ಕಲಿಕಾ ಸಂಗಾತಿ',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    welcomeTitle: 'Lernzy ಗೆ ಸ್ವಾಗತ',
    welcomeBody: 'ಗಣಿತ, ವಿಜ್ಞಾನ, ಇಂಗ್ಲಿಷ್ ಮತ್ತು ಇನ್ನಷ್ಟು ವಿಷಯಗಳನ್ನು ನಿಮ್ಮ ತರಗತಿ ಮತ್ತು ಆಸಕ್ತಿಗಳಿಗೆ ತಕ್ಕಂತೆ ಕಲಿಯಿರಿ.',
    languageTitle: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    languageSubtitle: 'Lernzy ನಿಮಗೆ ಕಲಿಸಲು ಬಳಸಬೇಕಾದ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    continue: 'ಮುಂದುವರಿಸಿ',
    languages: {
      en: { title: 'English', subtitle: 'ಪಾಠಗಳು ಮತ್ತು ಮೆನುಗಳಿಗೆ English ಬಳಸಿ' },
      hi: { title: 'Hindi', subtitle: 'ಪಾಠಗಳು ಮತ್ತು ಮೆನುಗಳಿಗೆ Hindi ಬಳಸಿ' },
      kn: { title: 'Kannada', subtitle: 'ಪಾಠಗಳು ಮತ್ತು ಮೆನುಗಳಿಗೆ Kannada ಬಳಸಿ' },
    },
    nameTitle: 'ನಿಮ್ಮ ಹೆಸರು ಏನು?',
    nameSubtitle: 'ಪಾಠಗಳನ್ನು ವೈಯಕ್ತಿಕವಾಗಿಸಲು ನಿಮ್ಮ ಟ್ಯೂಟರ್ ಇದನ್ನು ಬಳಸುತ್ತದೆ.',
    namePlaceholder: 'ನಿಮ್ಮ ಹೆಸರು ಬರೆಯಿರಿ',
    next: 'ಮುಂದೆ',
    gradeTitle: 'ನಿಮ್ಮ ತರಗತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    gradeSubtitle: 'Lernzy ನಿಮ್ಮ ಮಟ್ಟಕ್ಕೆ ತಕ್ಕ ಉದಾಹರಣೆಗಳು ಮತ್ತು ಅಭ್ಯಾಸ ನೀಡುತ್ತದೆ.',
    classLabel: (grade: number) => `ತರಗತಿ ${grade}`,
    interestsTitle: 'ನಿಮಗೆ ಏನು ಇಷ್ಟ?',
    interestsSubtitle: 'ಕನಿಷ್ಠ ಒಂದನ್ನು ಆಯ್ಕೆಮಾಡಿ. Lernzy ಉದಾಹರಣೆಗಳಲ್ಲಿ ಇವುಗಳನ್ನು ಬಳಸುತ್ತದೆ.',
    interests: {
      space: { title: 'ಅಂತರಿಕ್ಷ', subtitle: 'ಗ್ರಹಗಳು, ರಾಕೆಟ್‌ಗಳು ಮತ್ತು ನಕ್ಷತ್ರಗಳು' },
      nature: { title: 'ಪ್ರಕೃತಿ', subtitle: 'ಸಸ್ಯಗಳು ಮತ್ತು ಪ್ರಕೃತಿಯ ಲೋಕ' },
      robots: { title: 'ತಂತ್ರಜ್ಞಾನ', subtitle: 'ಕಂಪ್ಯೂಟರ್‌ಗಳು, ರೋಬೋಟ್‌ಗಳು ಮತ್ತು ಆಪ್‌ಗಳು' },
      sports: { title: 'ಕ್ರೀಡೆ', subtitle: 'ಆಟಗಳು, ಸ್ಕೋರ್‌ಗಳು ಮತ್ತು ತಂಡ ಕೆಲಸ' },
      stories: { title: 'ಕಥೆಗಳು', subtitle: 'ಪಾತ್ರಗಳು, ಕವಿತೆಗಳು ಮತ್ತು ಆಲೋಚನೆಗಳು' },
      history: { title: 'ಇತಿಹಾಸ', subtitle: 'ಸ್ಥಳಗಳು, ಜನರು ಮತ್ತು ಘಟನೆಗಳು' },
    },
    learningTitle: 'ನೀವು ಹೇಗೆ ಚೆನ್ನಾಗಿ ಕಲಿಯುತ್ತೀರಿ?',
    learningSubtitle: 'ಒಂದು ಶೈಲಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ. ಇದನ್ನು ನಂತರ ಬದಲಾಯಿಸಬಹುದು.',
    learningStyles: {
      reading: { title: 'ಓದಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ', subtitle: 'ಸ್ಪಷ್ಟ ಟಿಪ್ಪಣಿಗಳು, ಕಥೆಗಳು ಮತ್ತು ಚಿತ್ರಗಳು.' },
      audio: { title: 'ಕೇಳಿ ಕಲಿಯಿರಿ', subtitle: 'ಆಡಿಯೋಗೆ ಅನುಕೂಲವಾದ ಪಾಠಗಳು ಮತ್ತು ವಿವರಣೆಗಳು.' },
      quiz: { title: 'ಅಭ್ಯಾಸ ಮತ್ತು ಆಟ', subtitle: 'ಕ್ವಿಜ್‌ಗಳು, ಕಾರ್ಡ್‌ಗಳು ಮತ್ತು ಚಿಕ್ಕ ಸವಾಲುಗಳು.' },
    },
    doneTitleReady: 'ನೀವು ಸಿದ್ಧರಾಗಿದ್ದೀರಿ',
    doneTitleLoading: 'ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ',
    doneSubtitleReady: 'ನಿಮ್ಮ ಕಲಿಕಾ ಸ್ಥಳ ಸಿದ್ಧವಾಗಿದೆ.',
    doneSubtitleLoading: 'ನಿಮ್ಮ ಸ್ಥಳೀಯ ಕಲಿಕಾ ಪ್ರೊಫೈಲ್ ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ.',
    startLearning: 'ಕಲಿಯಲು ಪ್ರಾರಂಭಿಸಿ',
    preparing: 'ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ...',
    doneOk: 'ಸರಿ',
    doneBodyReady: 'ಈಗ ನೀವು ಪಾಠಗಳು, ಕ್ವಿಜ್‌ಗಳು, ಪ್ರಗತಿ ಮತ್ತು ರಿವ್ಯೂ ಕಾರ್ಡ್‌ಗಳನ್ನು ನೋಡಬಹುದು.',
    doneBodyLoading: 'ಇದಕ್ಕೆ ಒಂದು ಕ್ಷಣ ಮಾತ್ರ ಬೇಕು.',
  },
} as const;

export function getOnboardingCopy(language: LanguageCode) {
  return onboardingCopy[language] || onboardingCopy.en;
}
